import { supabase } from './supabase'

const MARK='[TRIAL_RESULT]'
const norm=s=>String(s||'').toLowerCase().replace(/[^a-z0-9\u3400-\u9fff]/g,'')
const esc=(s='')=>String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))
const monthNow=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`}
function parseTSV(text){return String(text||'').replace(/\r/g,'').split('\n').filter(x=>x.trim()).map(line=>line.split('\t'))}
function classify(item=''){const s=String(item).replace(/\s+/g,' ').trim();if(/廣告試堂未開卡|廣告試堂冇開卡/i.test(s))return'ad_noopen';if(/my\s*gift\s*試堂未開卡/i.test(s))return'mygift_noopen';if(/my\s*gift.*開卡/i.test(s))return'mygift_open';if(/新常規B.*送試堂/i.test(s))return'new_b_trial';if(/新常規A/i.test(s))return'new_a';if(/送一位朋友/i.test(s))return'friend_trial';return''}
function parseSheet(text){return parseTSV(text).map(c=>{while(c.length<7)c.push('');return{day:parseInt(c[0],10)||null,branch:String(c[1]||'').trim(),source:String(c[2]||'').trim(),owner:String(c[3]||'').trim(),name:String(c[5]||'').replace(/\s+/g,' ').trim(),item:String(c[6]||'').replace(/\s+/g,' ').trim(),kind:classify(c[6])}}).filter(r=>r.name||r.item)}
function expected(rows){const x={ad_noopen:0,mygift_noopen:0,mygift_open:0,new_b_trial:0,new_a:0,friend_trial:0};rows.forEach(r=>{if(r.kind)x[r.kind]++});return{...x,total:Object.values(x).reduce((a,b)=>a+b,0)}}
function appStats(store,month){const list=(store.clients||[]).filter(c=>String(c.trial_date||'').slice(0,7)===month);const out={total:list.length,ad_noopen:0,mygift_noopen:0,opened:0};list.forEach(c=>{const r=String(c.remark||'');if(r.includes('|no_open_mygift'))out.mygift_noopen++;else if(r.includes('|no_open_normal')||r.includes('|no_open|'))out.ad_noopen++;else if(r.includes('|opened_'))out.opened++});return out}
function bestClient(store,name){const n=norm(name);if(!n)return null;const exact=(store.clients||[]).find(c=>norm(c.name)===n);if(exact)return exact;const near=(store.clients||[]).filter(c=>{const cn=norm(c.name);return cn&&n.length>=4&&(cn.includes(n)||n.includes(cn))});return near.length===1?near[0]:null}
function dateFor(month,day){const [y,m]=month.split('-').map(Number),last=new Date(y,m,0).getDate(),d=Math.max(1,Math.min(last,+day||1));return `${month}-${String(d).padStart(2,'0')}T12:00`}
function resultLabel(raw=''){const s=String(raw);if(s.includes('|no_open_mygift'))return'朋友介紹 / MyGift 試堂未開卡';if(s.includes('|no_open_normal')||s.includes('|no_open|'))return'廣告試堂未開卡';if(s.includes('|opened_small'))return'試堂後開 10 點卡';if(s.includes('|opened_big'))return'試堂後開 35 點卡';if(s.includes('|no_show'))return'試堂沒有出席';return'試堂結果已記錄'}
function cleanVisibleMarkers(){document.querySelectorAll('#app-main *').forEach(el=>{if(el.children.length)return;const t=el.textContent||'';if(!t.includes(MARK))return;const before=t.replace(/\n?\[TRIAL_RESULT\]\|[^\n]*/g,'').trim();el.textContent=before?`${before} · ${resultLabel(t)}`:`📝 ${resultLabel(t)}`;el.classList.add('tf-clean-result')})}
async function bindReferrers(store){for(const c of store.clients||[]){if(c.referred_by_id)continue;const m=String(c.remark||'').match(/\|referrer=([^\n|]+)/);if(!m)continue;const ref=bestClient(store,m[1]);if(!ref||String(ref.id)===String(c.id))continue;const {error}=await supabase.from('clients').update({referred_by_id:ref.id}).eq('id',c.id);if(!error)c.referred_by_id=ref.id}}
function enhanceRefInputs(store){document.querySelectorAll('[data-final-referrer]').forEach(inp=>{if(inp.dataset.bindEnhanced)return;inp.dataset.bindEnhanced='1';const msg=document.createElement('div');msg.className='tf-ref-bind';inp.insertAdjacentElement('afterend',msg);const check=()=>{const v=inp.value.trim(),hit=bestClient(store,v);if(!v){msg.textContent='請輸入介紹人姓名，系統會搜尋現有客戶';msg.dataset.ok=''}else if(hit){msg.textContent=`✓ 已找到並會綁定：${hit.name}${hit.phone?' · '+hit.phone:''}`;msg.dataset.ok='1';inp.dataset.referrerId=hit.id}else{msg.textContent='⚠️ 找不到現有客戶，請先確認姓名';msg.dataset.ok='';inp.dataset.referrerId=''}};inp.addEventListener('input',check);inp.addEventListener('change',check);check()})}
function openAudit(store){const root=document.createElement('div');root.className='tf-backdrop tf-audit';root.innerHTML=`<div class="tf-card"><div class="tf-head"><div class="tf-title">📋 月份事蹟核對</div><button class="tf-close">×</button></div><div class="tf-audit-grid"><label>月份<input type="month" data-am value="${monthNow()}"></label></div><div class="tf-filter-note">直接 Copy 試算表整段文字貼入。系統會用同一套規則計算「總試堂」，再同 App 資料逐項核對。</div><textarea data-at placeholder="貼上整段試算表文字"></textarea><button class="tf-save" data-check>分析及核對</button><div data-report></div></div>`;document.body.appendChild(root);root.querySelector('.tf-close').onclick=()=>root.remove();root.querySelector('[data-check]').onclick=()=>{const rows=parseSheet(root.querySelector('[data-at]').value),e=expected(rows),a=appStats(store,root.querySelector('[data-am]').value),diff=e.total-a.total;root.__rows=rows;const labels=[['廣告試堂未開卡',e.ad_noopen,a.ad_noopen],['MyGift 試堂未開卡',e.mygift_noopen,a.mygift_noopen],['MyGift 開卡',e.mygift_open,'—'],['新常規A',e.new_a,'—'],['新常規B 送試堂',e.new_b_trial,'—'],['送一位朋友',e.friend_trial,'—']];root.querySelector('[data-report]').innerHTML=`<div class="tf-audit-total ${diff?'bad':'ok'}"><b>試算表總試堂：${e.total}</b><b>App 有試堂日期：${a.total}</b><strong>${diff===0?'✓ 數目一致':`相差 ${diff>0?'+':''}${diff}`}</strong></div>${labels.map(x=>`<div class="tf-audit-line"><span>${x[0]}</span><b>${x[1]}</b><span>App ${x[2]}</span></div>`).join('')}<div class="tf-audit-note">計算口徑：新常規A + 新常規B送試堂 + 廣告未開卡 + MyGift未開卡 + MyGift開卡 + 送一位朋友。你今次貼的表按這個口徑應該是 <b>${e.total}</b> 次。</div><button class="tf-save" data-repair>修正 App 試堂日期 / 結果</button>`;root.querySelector('[data-repair]').onclick=async()=>{const month=root.querySelector('[data-am]').value;let fixed=0,missing=0;for(const r of rows.filter(x=>x.kind&&x.day&&x.name&&x.kind!=='friend_trial')){const c=bestClient(store,r.name);if(!c){missing++;continue}const patch={trial_date:dateFor(month,r.day),branch:r.branch||c.branch};const old=String(c.remark||'');if(!old.includes(MARK)&&(r.kind==='ad_noopen'||r.kind==='mygift_noopen')){const outcome=r.kind==='mygift_noopen'?'no_open_mygift':'no_open_normal';patch.remark=[old,`${MARK}|${new Date(patch.trial_date).toISOString()}|${outcome}|monthly-audit`].filter(Boolean).join('\n');patch.status='prospect'}const {error}=await supabase.from('clients').update(patch).eq('id',c.id);if(!error){Object.assign(c,patch);fixed++}}await bindReferrers(store);alert(`完成修正 ${fixed} 位；找不到現有客戶 ${missing} 位。重新按「分析及核對」可再對數。`)}}
}
function addAuditButton(store){const tools=document.querySelector('.tf-tools');if(!tools||tools.querySelector('[data-month-audit]'))return;const b=document.createElement('button');b.className='tf-tool';b.dataset.monthAudit='1';b.textContent='📋 月結核對';b.onclick=()=>openAudit(store);tools.appendChild(b)}
export function installTrialMonthlyAuditFix(store){if(window.__trialMonthlyAuditFix)return;window.__trialMonthlyAuditFix=true;const st=document.createElement('style');st.textContent=`.tf-clean-result{color:#475569!important;font-size:13px!important;overflow-wrap:anywhere}.tf-ref-bind{font-size:12px;font-weight:800;color:#dc2626;margin:4px 2px 0}.tf-ref-bind[data-ok="1"]{color:#15803d}.tf-audit textarea{width:100%;min-height:190px;margin:10px 0;padding:12px;border:1px solid #cbd5e1;border-radius:14px;font-size:14px;box-sizing:border-box}.tf-audit-grid input{width:100%;padding:11px;border:1px solid #cbd5e1;border-radius:12px;margin:6px 0 10px}.tf-audit-total{display:grid;gap:5px;margin:12px 0;padding:12px;border-radius:14px}.tf-audit-total.ok{background:#ecfdf5;color:#047857}.tf-audit-total.bad{background:#fff7ed;color:#c2410c}.tf-audit-line{display:grid;grid-template-columns:1fr 45px 80px;gap:8px;padding:8px 2px;border-bottom:1px solid #e2e8f0;font-size:13px}.tf-audit-note{padding:12px;margin:10px 0;background:#f8fafc;border-radius:12px;font-size:13px;line-height:1.5}`;document.head.appendChild(st);const refresh=()=>{cleanVisibleMarkers();enhanceRefInputs(store);addAuditButton(store)};refresh();new MutationObserver(refresh).observe(document.body,{childList:true,subtree:true});store.$subscribe?.(()=>refresh(),{detached:true});setTimeout(()=>bindReferrers(store),1800)}
