import { supabase } from './supabase'

const MARK='[TRIAL_RESULT]'
const norm=s=>String(s||'').toLowerCase().replace(/[（）()【】\[\]「」『』]/g,' ').replace(/my\s*gift/gi,' ').replace(/fd\b/gi,' ').replace(/[^a-z0-9\u3400-\u9fff]/g,'')
const esc=(s='')=>String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))
const monthNow=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`}
const mainName=s=>String(s||'').replace(/[（(].*$/,'').replace(/\*\s*\d+\s*位?/g,'').replace(/^\d{7,12}\s+/,'').trim()
function parseTSV(text){return String(text||'').replace(/\r/g,'').split('\n').filter(x=>x.trim()).map(line=>line.split('\t'))}
function classify(item=''){
  const s=String(item).replace(/\s+/g,' ').trim()
  if(/my\s*gift\s*試堂未開卡/i.test(s))return'mygift_noopen'
  if(/廣告試堂未開卡|廣告試堂冇開卡/i.test(s))return'ad_noopen'
  if(/my\s*gift.*開卡.*b|my\s*gift.*b.*套票/i.test(s))return'opened_big'
  if(/my\s*gift.*開卡.*a/i.test(s))return'opened_small'
  if(/常規\s*b.*送試堂|新常規\s*b/i.test(s))return'opened_big'
  if(/新常規\s*a/i.test(s))return'opened_small'
  if(/送一位朋友/i.test(s))return'friend_trial'
  return''
}
function kindLabel(k){return({ad_noopen:'廣告・出席未開卡',mygift_noopen:'MyGift・出席未開卡',opened_small:'小卡（常規A）',opened_big:'大卡（常規B）',friend_trial:'送一位朋友'}[k]||'未分類')}
function parseSheet(text){
  return parseTSV(text).map((c,i)=>{while(c.length<7)c.push('');const name=String(c[5]||'').replace(/\s+/g,' ').trim(),item=String(c[6]||'').replace(/\s+/g,' ').trim();return{id:`s${i}`,day:parseInt(c[0],10)||null,branch:String(c[1]||'').trim(),source:String(c[2]||'').trim(),owner:String(c[3]||'').trim(),name,matchName:mainName(name),item,kind:classify(item)}}).filter(r=>r.name||r.item)
}
function isTrialSheetRow(r){return !!r.kind&&r.kind!=='friend_trial'}
function dateFor(month,day){const [y,m]=month.split('-').map(Number),last=new Date(y,m,0).getDate(),d=Math.max(1,Math.min(last,+day||1));return `${month}-${String(d).padStart(2,'0')}T12:00`}
function appResult(c){const s=String(c.remark||'');if(s.includes('|no_open_mygift'))return'mygift_noopen';if(s.includes('|no_open_normal')||s.includes('|no_open|'))return'ad_noopen';if(s.includes('|opened_big'))return'opened_big';if(s.includes('|opened_small'))return'opened_small';return''}
function resultLabel(raw=''){const s=String(raw);if(s.includes('|no_open_mygift'))return'朋友介紹 / MyGift 試堂未開卡';if(s.includes('|no_open_normal')||s.includes('|no_open|'))return'廣告試堂未開卡';if(s.includes('|opened_small'))return'試堂後開小卡';if(s.includes('|opened_big'))return'試堂後開大卡';if(s.includes('|no_show'))return'試堂沒有出席';return'試堂結果已記錄'}
function cleanVisibleMarkers(){document.querySelectorAll('#app-main *').forEach(el=>{if(el.children.length)return;const t=el.textContent||'';if(!t.includes(MARK))return;const before=t.replace(/\n?\[TRIAL_RESULT\]\|[^\n]*/g,'').trim();el.textContent=before?`${before} · ${resultLabel(t)}`:`📝 ${resultLabel(t)}`;el.classList.add('tf-clean-result')})}
function scoreNames(a,b){const x=norm(mainName(a)),y=norm(mainName(b));if(!x||!y)return 0;if(x===y)return 100;if(x.length>=3&&y.length>=3&&(x.includes(y)||y.includes(x)))return 82;const ax=new Set(x.split('')),ay=new Set(y.split(''));const inter=[...ax].filter(v=>ay.has(v)).length;return Math.round(60*inter/Math.max(ax.size,ay.size))}
function bestClient(store,name){const ranked=(store.clients||[]).map(c=>({c,s:scoreNames(c.name,name)})).sort((a,b)=>b.s-a.s);return ranked[0]?.s>=82?ranked[0].c:null}
async function bindReferrers(store){for(const c of store.clients||[]){if(c.referred_by_id)continue;const m=String(c.remark||'').match(/\|referrer=([^\n|]+)/);if(!m)continue;const ref=bestClient(store,m[1]);if(!ref||String(ref.id)===String(c.id))continue;const {error}=await supabase.from('clients').update({referred_by_id:ref.id}).eq('id',c.id);if(!error)c.referred_by_id=ref.id}}
function enhanceRefInputs(store){document.querySelectorAll('[data-final-referrer]').forEach(inp=>{if(inp.dataset.bindEnhanced)return;inp.dataset.bindEnhanced='1';const msg=document.createElement('div');msg.className='tf-ref-bind';inp.insertAdjacentElement('afterend',msg);const check=()=>{const v=inp.value.trim(),hit=bestClient(store,v);if(!v){msg.textContent='請輸入介紹人姓名，系統會搜尋現有客戶';msg.dataset.ok=''}else if(hit){msg.textContent=`✓ 已找到並會綁定：${hit.name}${hit.phone?' · '+hit.phone:''}`;msg.dataset.ok='1';inp.dataset.referrerId=hit.id}else{msg.textContent='⚠️ 找不到現有客戶，請先確認姓名';msg.dataset.ok='';inp.dataset.referrerId=''}};inp.addEventListener('input',check);inp.addEventListener('change',check);check()})}
function autoMatch(appRows,sheetRows){
  const used=new Set(),pairs=[]
  for(const c of appRows){let best=null;for(const r of sheetRows){if(used.has(r.id))continue;let s=scoreNames(c.name,r.matchName||r.name);if(c.branch&&r.branch&&c.branch===r.branch)s+=5;const ad=Number(String(c.trial_date||'').slice(8,10)),sd=Number(r.day||0);if(ad&&sd&&ad===sd)s+=8;if(!best||s>best.score)best={row:r,score:s}}if(best&&best.score>=82){used.add(best.row.id);pairs.push({client:c,sheet:best.row,score:Math.min(best.score,100),manual:false})}else pairs.push({client:c,sheet:null,score:0,manual:false})}
  return{pairs,unmatched:sheetRows.filter(r=>!used.has(r.id))}
}
function sheetOptions(rows,selected=''){return `<option value="">— 未配對 —</option>${rows.map(r=>`<option value="${r.id}" ${r.id===selected?'selected':''}>${esc(r.day||'?')}日｜${esc(r.name)}｜${esc(kindLabel(r.kind))}</option>`).join('')}`}
function clientOptions(store,selected=''){return `<option value="">— 選現有客戶 —</option>${(store.clients||[]).map(c=>`<option value="${esc(c.id)}" ${String(c.id)===String(selected)?'selected':''}>${esc(c.name)}${c.phone?'｜'+esc(c.phone):''}</option>`).join('')}`}
function renderAudit(root,store){
  const month=root.querySelector('[data-am]').value,rows=parseSheet(root.querySelector('[data-at]').value),sheetRows=rows.filter(isTrialSheetRow),appRows=(store.clients||[]).filter(c=>String(c.trial_date||'').slice(0,7)===month),m=autoMatch(appRows,sheetRows)
  root.__audit={month,rows,sheetRows,appRows,pairs:m.pairs,unmatched:m.unmatched}
  const matched=m.pairs.filter(p=>p.sheet).length,appMissing=m.pairs.length-matched,sheetMissing=m.unmatched.length
  root.querySelector('[data-report]').innerHTML=`
    <div class="tf-audit-summary"><div><small>App 試堂</small><b>${appRows.length}</b></div><div><small>試算表候選</small><b>${sheetRows.length}</b></div><div class="ok"><small>自動配對</small><b>${matched}</b></div><div class="${appMissing+sheetMissing?'bad':'ok'}"><small>待處理</small><b>${appMissing+sheetMissing}</b></div></div>
    <div class="tf-audit-note">核對口徑已統一：<b>常規A＝小卡、常規B＝大卡</b>；「新／續」不作配對條件，由 App 自己的購買紀錄判斷。廣告未開卡及 MyGift 未開卡都代表<b>已出席但沒有開卡</b>。</div>
    <h3>① App ${appRows.length} 位逐人對試算表</h3>
    <div class="tf-person-list">${m.pairs.map((p,i)=>`<div class="tf-person ${p.sheet?'matched':'missing'}"><div class="tf-person-head"><b>${esc(p.client.name)}</b><span>${p.sheet?'✓ '+p.score+'%':'⚠️ 未匹配'}</span></div><div class="tf-person-sub">App：${esc(String(p.client.trial_date||'').slice(5,10))} · ${esc(p.client.branch||'')} · ${esc(kindLabel(appResult(p.client)))}</div><select data-pair="${i}">${sheetOptions(sheetRows,p.sheet?.id||'')}</select><div class="tf-person-sub" data-pair-info>${p.sheet?`試算表：${esc(p.sheet.name)} · ${esc(kindLabel(p.sheet.kind))}`:'請手動選擇對應試算表紀錄'}</div></div>`).join('')}</div>
    <h3>② 試算表有、App 未自動配到</h3>
    <div class="tf-unmatched">${m.unmatched.length?m.unmatched.map(r=>`<div class="tf-person missing" data-sheet-missing="${r.id}"><div class="tf-person-head"><b>${esc(r.name)}</b><span>試算表獨有</span></div><div class="tf-person-sub">${r.day||'?'}日 · ${esc(r.branch)} · ${esc(kindLabel(r.kind))}</div><select data-existing="${r.id}">${clientOptions(store)}</select><button class="tf-mini" data-add="${r.id}">＋ 新增為試堂客戶</button></div>`).join(''):'<div class="tf-all-good">✓ 沒有試算表獨有紀錄</div>'}</div>
    <div class="tf-audit-actions"><button class="tf-save" data-preview>重新自動配對</button><button class="tf-save primary" data-apply>確認配對並修正 App</button></div>`
  root.querySelectorAll('[data-pair]').forEach(sel=>sel.onchange=()=>{const p=m.pairs[Number(sel.dataset.pair)],r=sheetRows.find(x=>x.id===sel.value);p.sheet=r||null;p.manual=true;const info=sel.parentElement.querySelector('[data-pair-info]');info.textContent=r?`試算表：${r.name} · ${kindLabel(r.kind)}`:'請手動選擇對應試算表紀錄'})
  root.querySelectorAll('[data-existing]').forEach(sel=>sel.onchange=()=>{const r=m.unmatched.find(x=>x.id===sel.dataset.existing);if(r)r.manualClientId=sel.value||''})
  root.querySelectorAll('[data-add]').forEach(btn=>btn.onclick=async()=>{const r=m.unmatched.find(x=>x.id===btn.dataset.add);if(!r)return;btn.disabled=true;btn.textContent='新增中…';const {data:{session}}=await supabase.auth.getSession();const payload={name:mainName(r.name)||r.name,phone:'',branch:r.branch||'觀塘',status:'prospect',trial_date:dateFor(month,r.day),owner_email:session?.user?.email};const {data,error}=await supabase.from('clients').insert(payload).select().single();if(error){alert('新增失敗：'+error.message);btn.disabled=false;btn.textContent='＋ 新增為試堂客戶';return}store.clients.unshift(data);navigator.vibrate?.(35);renderAudit(root,store)})
  root.querySelector('[data-preview]').onclick=()=>renderAudit(root,store)
  root.querySelector('[data-apply]').onclick=async()=>{
    const button=root.querySelector('[data-apply]');button.disabled=true;button.textContent='正在修正…';let fixed=0,failed=0
    const work=[]
    m.pairs.forEach(p=>{if(p.sheet)work.push({c:p.client,r:p.sheet})})
    m.unmatched.forEach(r=>{if(r.manualClientId){const c=(store.clients||[]).find(x=>String(x.id)===String(r.manualClientId));if(c)work.push({c,r})}})
    const seen=new Set()
    for(const {c,r} of work){const key=String(c.id);if(seen.has(key))continue;seen.add(key);const patch={trial_date:dateFor(month,r.day),branch:r.branch||c.branch};const old=String(c.remark||''),hasResult=old.includes(MARK);if(!hasResult&&(r.kind==='ad_noopen'||r.kind==='mygift_noopen')){const outcome=r.kind==='mygift_noopen'?'no_open_mygift':'no_open_normal';patch.remark=[old,`${MARK}|${new Date(patch.trial_date).toISOString()}|${outcome}|monthly-audit`].filter(Boolean).join('\n');patch.status='prospect'}const {error}=await supabase.from('clients').update(patch).eq('id',c.id);if(error)failed++;else{Object.assign(c,patch);fixed++}}
    navigator.vibrate?.([35,35,55]);alert(`完成：已修正 ${fixed} 位${failed?`；失敗 ${failed} 位`:''}。`);renderAudit(root,store)
  }
}
function openAudit(store){const root=document.createElement('div');root.className='tf-backdrop tf-audit';root.innerHTML=`<div class="tf-card"><div class="tf-head"><div class="tf-title">📋 月份試堂逐人核對</div><button class="tf-close">×</button></div><div class="tf-audit-grid"><label>核對月份<input type="month" data-am value="${monthNow()}"></label></div><div class="tf-filter-note">貼上該月 Google Sheets / Excel 整段資料。先抓 App 當月所有試堂，再逐人自動匹配；配不到可手動配對或新增。</div><textarea data-at placeholder="貼上整段試算表文字"></textarea><button class="tf-save primary" data-check>分析及逐人核對</button><div data-report></div></div>`;document.body.appendChild(root);root.querySelector('.tf-close').onclick=()=>root.remove();root.querySelector('[data-check]').onclick=()=>renderAudit(root,store)}
function addAuditButton(store){const tools=document.querySelector('.tf-tools');if(!tools||tools.querySelector('[data-month-audit]'))return;const b=document.createElement('button');b.className='tf-tool';b.dataset.monthAudit='1';b.textContent='📋 月結核對';b.onclick=()=>openAudit(store);tools.appendChild(b)}
export function installTrialMonthlyAuditFix(store){if(window.__trialMonthlyAuditFix)return;window.__trialMonthlyAuditFix=true;const st=document.createElement('style');st.textContent=`.tf-clean-result{color:#475569!important;font-size:13px!important;overflow-wrap:anywhere}.tf-ref-bind{font-size:12px;font-weight:800;color:#dc2626;margin:4px 2px 0}.tf-ref-bind[data-ok="1"]{color:#15803d}.tf-audit .tf-card{max-height:92dvh;overflow:auto}.tf-audit textarea{width:100%;min-height:170px;margin:10px 0;padding:12px;border:1px solid #cbd5e1;border-radius:14px;font-size:14px;box-sizing:border-box}.tf-audit-grid input,.tf-person select{width:100%;padding:11px;border:1px solid #cbd5e1;border-radius:12px;margin:6px 0 10px;background:#fff;font-size:14px}.tf-audit-summary{display:grid;grid-template-columns:repeat(4,1fr);gap:7px;margin:14px 0}.tf-audit-summary>div{background:#f8fafc;border-radius:13px;padding:10px 6px;text-align:center}.tf-audit-summary small{display:block;color:#64748b;font-size:11px}.tf-audit-summary b{display:block;font-size:22px;margin-top:3px}.tf-audit-summary .ok b{color:#059669}.tf-audit-summary .bad b{color:#dc2626}.tf-audit-note{padding:12px;margin:10px 0;background:#f8fafc;border-radius:12px;font-size:13px;line-height:1.55}.tf-audit h3{font-size:15px;margin:18px 2px 8px}.tf-person{border:1.5px solid #dbe3ee;border-radius:15px;padding:12px;margin:8px 0;background:#fff}.tf-person.matched{border-color:#bbf7d0}.tf-person.missing{border-color:#fecaca;background:#fffafa}.tf-person-head{display:flex;justify-content:space-between;gap:8px;align-items:center}.tf-person-head span{font-size:11px;font-weight:800;color:#64748b}.tf-person.matched .tf-person-head span{color:#059669}.tf-person.missing .tf-person-head span{color:#dc2626}.tf-person-sub{font-size:12px;color:#64748b;line-height:1.45;margin:5px 0}.tf-mini{width:100%;padding:10px;border:1px dashed #818cf8;border-radius:11px;background:#eef2ff;color:#4338ca;font-weight:800}.tf-audit-actions{position:sticky;bottom:-1px;background:#fff;padding:10px 0 4px;display:grid;grid-template-columns:1fr 1.3fr;gap:8px}.tf-save.primary{background:#4f46e5!important;color:white!important}.tf-all-good{padding:14px;background:#ecfdf5;color:#047857;border-radius:12px;font-weight:800}@media(max-width:480px){.tf-audit-summary{grid-template-columns:repeat(2,1fr)}.tf-audit-actions{grid-template-columns:1fr}.tf-audit .tf-card{max-height:94dvh}}`;document.head.appendChild(st);const refresh=()=>{cleanVisibleMarkers();enhanceRefInputs(store);addAuditButton(store)};refresh();new MutationObserver(refresh).observe(document.body,{childList:true,subtree:true});store.$subscribe?.(()=>refresh(),{detached:true});setTimeout(()=>bindReferrers(store),1800)}
