import { supabase } from './supabase'

const MARK='[TRIAL_RESULT]'
const HOURS=12
const css=`
.tf-backdrop{position:fixed;inset:0;background:#0f172ab8;z-index:99990;display:flex;align-items:center;justify-content:center;padding:8vh 5vw}.tf-card{width:min(560px,100%);max-height:84vh;overflow:auto;background:#fff;border-radius:28px;padding:22px;box-shadow:0 24px 70px #0005;color:#172033}.tf-head{display:flex;justify-content:space-between;gap:12px;align-items:start}.tf-title{font-size:24px;font-weight:900}.tf-close{border:0;border-radius:50%;width:42px;height:42px;font-size:22px;background:#f1f5f9}.tf-info{margin:14px 0;background:#f8fafc;border-radius:18px;padding:14px;line-height:1.65}.tf-actions{display:grid;gap:10px}.tf-btn{border:1px solid #dbe3ef;background:#fff;border-radius:17px;padding:15px;text-align:left;font-size:17px;font-weight:800}.tf-btn.primary{background:#eef2ff;border-color:#818cf8;color:#4338ca}.tf-sub{display:none;gap:10px;margin-top:10px}.tf-sub.show{display:grid;grid-template-columns:1fr 1fr}.tf-sub button{padding:14px;border:0;border-radius:15px;font-weight:800;background:#4f46e5;color:white}.tf-res{display:none;margin-top:10px}.tf-res.show{display:grid;gap:9px}.tf-res input{font-size:16px;padding:13px;border:1px solid #cbd5e1;border-radius:14px}.tf-save{border:0;border-radius:15px;padding:14px;background:#16a34a;color:#fff;font-weight:900;font-size:16px}.tf-count{font-size:13px;color:#64748b;margin-top:12px;text-align:center}
.tf-summary{position:fixed;right:18px;bottom:100px;z-index:8000;background:#fff;border:1px solid #e2e8f0;border-radius:18px;padding:10px 14px;box-shadow:0 8px 25px #0f172a20;font-size:12px;color:#475569}.tf-summary b{color:#4f46e5}
`
function esc(s=''){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function trialTime(c){if(!c?.trial_date)return null;const d=new Date(String(c.trial_date).replace(' ','T'));return isNaN(d)?null:d}
function hasResult(c){return String(c?.remark||'').includes(MARK)}
function due(c){const d=trialTime(c);return d&&!hasResult(c)&&Date.now()-d.getTime()>=HOURS*3600000&&(String(c.status||'prospect').toLowerCase()==='prospect')}
function resultOf(c){const m=String(c.remark||'').match(/\[TRIAL_RESULT\]\|([^|]+)\|([^|\n]+)/);return m?{date:m[1],outcome:m[2]}:null}
function cleanRemark(r=''){return String(r).replace(/\n?\[TRIAL_RESULT\]\|[^\n]*/g,'').trim()}
async function saveResult(store,c,outcome,extra=''){
 const stamp=new Date().toISOString(); const marker=`${MARK}|${stamp}|${outcome}${extra?'|'+extra:''}`; const remark=[cleanRemark(c.remark),marker].filter(Boolean).join('\n');
 const patch={remark}; if(outcome==='no_show')patch.status='absent'; if(outcome==='opened_small'||outcome==='opened_big')patch.status='active';
 const {error}=await supabase.from('clients').update(patch).eq('id',c.id); if(error)throw error; Object.assign(c,patch); const local=store.clients.find(x=>x.id===c.id);if(local)Object.assign(local,patch)
}
async function reschedule(store,c,value){if(!value)throw new Error('請選擇新日期及時間');const remark=cleanRemark(c.remark);const patch={trial_date:value,status:'prospect',remark};const {error}=await supabase.from('clients').update(patch).eq('id',c.id);if(error)throw error;Object.assign(c,patch);const local=store.clients.find(x=>x.id===c.id);if(local)Object.assign(local,patch)}
function stats(store){const now=new Date(),y=now.getFullYear(),m=now.getMonth();const rows=store.clients.filter(c=>{const d=trialTime(c);return d&&d.getFullYear()===y&&d.getMonth()===m});let opened=0,attended=0,noOpen=0,noShow=0,pending=0;rows.forEach(c=>{const r=resultOf(c);if(!r){if(due(c))pending++;return}if(r.outcome.startsWith('opened_')){opened++;attended++}else if(r.outcome==='no_open'){noOpen++;attended++}else if(r.outcome==='no_show')noShow++});return{total:rows.length,opened,attended,noOpen,noShow,pending,rate:attended?opened/attended*100:0}}
function renderSummary(store){let el=document.getElementById('tf-summary');if(!el){el=document.createElement('div');el.id='tf-summary';el.className='tf-summary';document.body.appendChild(el)}const s=stats(store);el.innerHTML=`本月試堂 ${s.total}｜開卡 <b>${s.opened}</b>｜未開 ${s.noOpen}<br>到場開卡率 <b>${s.rate.toFixed(1)}%</b>${s.pending?`｜待跟進 ${s.pending}`:''}`}
function show(store,c,onDone){const d=trialTime(c);const root=document.createElement('div');root.className='tf-backdrop';root.innerHTML=`<div class="tf-card"><div class="tf-head"><div><div class="tf-title">📝 試堂結果跟進</div><div style="color:#64748b;margin-top:4px">試堂後已超過 12 小時</div></div><button class="tf-close">×</button></div><div class="tf-info"><b>${esc(c.name)}</b>　${esc(c.phone||'')}<br>📍 ${esc(c.branch||'')}<br>📅 ${d?d.toLocaleString('zh-HK',{hour12:false}):''}</div><div class="tf-actions"><button class="tf-btn primary" data-a="opened">✅ 開咗卡</button><div class="tf-sub"><button data-a="small">10點細卡</button><button data-a="big">35點大卡</button></div><button class="tf-btn" data-a="no_open">❌ 試堂後冇開卡</button><button class="tf-btn" data-a="no_show">🚫 冇出席</button><button class="tf-btn" data-a="move">📅 改咗其他日子</button><div class="tf-res"><input type="datetime-local"><button class="tf-save">確認新試堂時間</button></div></div><div class="tf-count">完成後會自動更新後台及本月開卡率</div></div>`;document.body.appendChild(root);const close=()=>root.remove();root.querySelector('.tf-close').onclick=close;root.querySelector('[data-a=opened]').onclick=()=>root.querySelector('.tf-sub').classList.toggle('show');root.querySelector('[data-a=move]').onclick=()=>root.querySelector('.tf-res').classList.toggle('show');const commit=async outcome=>{try{await saveResult(store,c,outcome);close();renderSummary(store);onDone()}catch(e){alert('更新失敗：'+e.message)}};root.querySelector('[data-a=small]').onclick=()=>commit('opened_small');root.querySelector('[data-a=big]').onclick=()=>commit('opened_big');root.querySelector('[data-a=no_open]').onclick=()=>commit('no_open');root.querySelector('[data-a=no_show]').onclick=()=>commit('no_show');root.querySelector('.tf-save').onclick=async()=>{try{await reschedule(store,c,root.querySelector('input').value);close();renderSummary(store);onDone()}catch(e){alert(e.message)}}}
export function installTrialFollowUp(store){if(document.getElementById('tf-style'))return;const s=document.createElement('style');s.id='tf-style';s.textContent=css;document.head.appendChild(s);let busy=false;const check=()=>{renderSummary(store);if(busy)return;const q=store.clients.filter(due);if(!q.length)return;busy=true;let i=0;const next=()=>{if(i>=q.length){busy=false;return}show(store,q[i++],next)};next()};setTimeout(check,3500);setInterval(check,5*60*1000);window.addEventListener('focus',()=>setTimeout(check,500))}
